// modules/javascript.js

/**
 * API Tadeo - MCP
 * Generador de proyectos JavaScript
 */

/**
 * Crea un archivo JavaScript personalizado.
 */
export function createJavaScript(filename = "script.js", code = "") {
    return {
        name: filename.endsWith(".js")
            ? filename
            : `${filename}.js`,
        content: code
    };
}

/**
 * Código JavaScript base.
 */
export function createDefaultJavaScript() {
    return `// Generated by API Tadeo - MCP

console.log("API Tadeo - MCP JavaScript Module");

function helloWorld(){
    return "Hello from JavaScript!";
}

document.addEventListener("DOMContentLoaded", () => {

    console.log(helloWorld());

});`;
}

/**
 * Genera un proyecto JavaScript completo.
 */
export function createJavaScriptProject(projectName = "JavaScriptProject") {
    return {
        name: projectName,
        files: [
            {
                name: "script.js",
                content: createDefaultJavaScript()
            }
        ]
    };
}

/**
 * Genera una función JavaScript.
 */
export function createFunction(name, parameters = [], body = "") {
    return `function ${name}(${parameters.join(", ")}) {
${body}
}`;
}

/**
 * Genera una clase JavaScript.
 */
export function createClass(name) {
    return `class ${name} {

    constructor(){

    }

}`;
}

/**
 * Genera un módulo ES6.
 */
export function createModule(name) {
    return `// ${name}.js

export default {

    init(){
        console.log("${name} loaded");
    }

};`;
}

/**
 * Combina archivos JavaScript.
 */
export function mergeJavaScript(files = []) {
    return files.join("\n\n");
}

/**
 * Minifica JavaScript básico.
 */
export function minifyJavaScript(code = "") {
    return code
        .replace(/\/\/.*$/gm, "")
        .replace(/\n/g, "")
        .replace(/\s+/g, " ")
        .trim();
}
