// modules/typescript.js

/**
 * API Tadeo - MCP
 * Generador TypeScript
 */

export function createTypeScript(filename = "index.ts", code = "") {
    return {
        name: filename.endsWith(".ts")
            ? filename
            : `${filename}.ts`,
        content: code
    };
}

export function createDefaultTypeScript() {
    return `// Generated by API Tadeo - MCP

interface User {
    name: string;
    age: number;
}

function hello(user: User): string {

    return "Hello " + user.name;

}

console.log(
    hello({
        name:"Tadeo",
        age:18
    })
);`;
}

export function createTSProject() {
    return {
        name:"TypeScriptProject",
        files:[
            {
                name:"index.ts",
                content:createDefaultTypeScript()
            }
        ]
    };
}
